package jsystem_3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;

public class sqlHelper {
	PreparedStatement ps = null;
	ResultSet rs = null;
	Connection ct =null;
	
	String url = "jdbc:sqlserver://LAPTOP-AVJCSDFI;DatabaseName=db_rider;";
	String security = "IntegratedSecurity=true;encrypt=true;trustServerCertificate=true";
	String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
	
	
	public Properties info() {
		Properties info = new Properties( );
		info.put("IntegratedSecurity", "true");
		info.put("encrypt", "true");
		info.put("trustServerCertificate", "true");
		return info;
	}
	
	// 將關閉數據庫動作封裝成一個類
	public void close() {
		try {
       		// 強化
       		if(rs!=null) {
       			rs.close();
       		}if(ct!=null) {
       			ct.close();
       		}if(ps!=null) {
       			ps.close();
       		}
		}catch(SQLException ex) {
			ex.printStackTrace();
		}
	}
	// 創建一個新的queryExecute，不帶注入參數
	public ResultSet queryExecute(String sql) {
		try {
			// 加載驅動
			Class.forName(driver);
			// 建立連接
			ct = DriverManager.getConnection(url, info());
			ps = ct.prepareStatement(sql);
			// 操作執行
			rs = ps.executeQuery();
		}catch(Exception e) {
			e.printStackTrace();
		}finally {
			// 關閉資源?????
			/* 想想在這邊關閉資源是沒意義的，
			 * 首先上面return執行後，就會直接跳出了，關閉資源不會被執行;
			 * 如果反過來先關閉資源，那return rs就會死胎，也不行
			 * 所以要將rs結果返回 數據模型層(stuModel2)
			 * 使用完後，由那端做關閉
			 * (題外話) 由數據模型層(它端)關閉我們的數據庫，會不會有權限安全問題
			 * 不會，因為函數是我這邊包裝好的[上面有一個封裝的class close()可以
			 * 執行關閉]，傳給它端用就可以了*/
			return rs;
		}
	}
	
	// 查詢數據庫的操作，返回的結果定為ResultSet屬性(之前沒用過)
	/* ResultSet: A table of data representing a database result set,
	 *  whichis usually generated by executing a statement that queries
	 *   the database.*/ 
	public ResultSet queryExecute(String sql, String[] paras) {
		try {
			// 加載驅動
			Class.forName(driver);
			// 建立連接
			ct = DriverManager.getConnection(url, info());
			ps = ct.prepareStatement(sql);
			// 應用，循環附值
			for(int i=0; i<paras.length; i++) {
				ps.setString(i+1, paras[i]);
			}
			// 操作執行
			rs = ps.executeQuery();
		}catch(Exception e) {
			e.printStackTrace();
		}finally {
			// 關閉資源?????
			/* 想想在這邊關閉資源是沒意義的，
			 * 首先上面return執行後，就會直接跳出了，關閉資源不會被執行;
			 * 如果反過來先關閉資源，那return rs就會死胎，也不行
			 * 所以要將rs結果返回 數據模型層(stuModel2)
			 * 使用完後，由那端做關閉
			 * (題外話) 由數據模型層(它端)關閉我們的數據庫，會不會有權限安全問題
			 * 不會，因為函數是我這邊包裝好的[上面有一個封裝的class close()可以
			 * 執行關閉]，傳給它端用就可以了*/
			return rs;
		}
	}
	// 一樣把增刪改合併載一起
	
	public boolean updExecute(String sql, String[] paras) {
		boolean b = true;
		try {
			// 加載驅動
			Class.forName(driver);
			// 建立連接
			ct = DriverManager.getConnection(url, info());
			ps = ct.prepareStatement(sql);
			// 應用，循環附值
			for(int i=0; i<paras.length; i++) {
				ps.setString(i+1, paras[i]);
			}
			// 操作執行，會回傳值1代表成功，查查其他情況勒
			if(ps.executeUpdate() != 1) {
				b = false;
			}
		}catch(Exception e) {
			b = false;
			e.printStackTrace();
		}finally {
			// 也將關閉數據庫動作，小小封裝起來
			this.close();
//			try {
//	       		// 強化
//	       		if(rs!=null) {
//	       			rs.close();
//	       		}if(ct!=null) {
//	       			ct.close();
//	       		}if(ps!=null) {
//	       			ps.close();
//	       		}
//			}catch(SQLException ex) {
//				ex.printStackTrace();
//			}
		}
		// return result in the end
		return b;
	}
}
